name: ðŸ› Bug Report
# title: " "
description: Problems with YOLOv6
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a YOLOv6 ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/meituan/YOLOv6/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: YOLOv6 Component
      description: |
        Please select the part of YOLOv6 where you found the bug.(è¯·é€‰æ‹©bugæ‰€åœ¨çš„æ¨¡å—)
      multiple: true
      options:
        - "Training"ï¼ˆè®­ç»ƒï¼‰
        - "Evaluation" ï¼ˆè¯„ä¼°ï¼‰
        - "Inference" ï¼ˆæŽ¨ç†åŠç»“æžœå¯è§†åŒ–ï¼‰
        - "Export"ï¼ˆæ¨¡åž‹å¯¼å‡ºï¼‰
        - "Quantization(including QAT, PTQ ...)"ï¼ˆé‡åŒ–éƒ¨åˆ†ï¼ŒåŒ…æ‹¬QATè®­ç»ƒï¼ŒPTQç­‰ï¼‰
        - "Multi-GPU"ï¼ˆå¤šå¡è®­ç»ƒï¼‰
        - "TensorRT"ï¼ˆTRTéƒ¨ç½²ï¼‰
        - "Other"ï¼ˆå…¶ä»–ï¼‰
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Provide console output with error messages and/or screenshots of the bug.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.ï¼ˆè¯·æä¾›bugç›¸å…³çš„æŠ¥é”™æ—¥å¿—æˆ–æˆªå›¾ç­‰è¯¦ç»†ä¿¡æ¯ï¼‰
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please specify the software and hardware you used to produce the bug.ï¼ˆè¿è¡ŒçŽ¯å¢ƒä¿¡æ¯ï¼‰
      placeholder: |
        - YOLO: YOLOv6 v2.0 torch 1.8.0+cu111 CUDA:0 (A100-SXM4-40GB, 40536MiB)
        - OS: Ubuntu 20.04
        - Python: 3.8
    validations:
      required: false

  - type: textarea
    attributes:
      label: Minimal Reproducible Example
      description: >
        When asking a question, people will be better able to provide help if you provide code that they can easily understand and use to **reproduce** the problem.ï¼ˆè¯·æä¾›èƒ½å¤çŽ°è¿™ä¸ªbugçš„ç›¸å…³å‘½ä»¤åŠé…ç½®è¶…å‚ç­‰ä¿¡æ¯ï¼‰
      placeholder: |
        ```
        # Code to reproduce your issue here
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/meituan/YOLOv6/pulls) (PR) to help improve YOLOv6 for everyone, especially if you have a good understanding of how to implement a fix or feature.
      options:
        - label: Yes I'd like to help by submitting a PR!
